# Generated by Django 2.2.5 on 2020-05-06 09:40

from django.db import migrations
import imagekit.models.fields
import utils.image_upload


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200421_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=utils.image_upload.upload_instance_image, verbose_name='фото'),
        ),
    ]
