# Generated by Django 2.2.5 on 2020-05-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_auto_20200427_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dyspnea', models.PositiveSmallIntegerField(choices=[(1, '- нет'), (2, '+ при нагрузке'), (3, '++ в покое')], default=1, verbose_name='одышка')),
                ('position_bed', models.PositiveSmallIntegerField(choices=[(1, '- горизонтально'), (2, '+ высоко на 2х подушках'), (3, '++ сидя')], default=1, verbose_name='положение в постели')),
                ('heartbeat', models.PositiveSmallIntegerField(choices=[(1, '- нет'), (2, '+ при нагрузке'), (3, '++ в покое')], default=1, verbose_name='сердцебиение')),
                ('stack', models.PositiveSmallIntegerField(choices=[(1, '- стопы'), (2, '+ голени'), (3, '++ выше колени')], default=1, verbose_name='стеки в ноге')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='вес (кг)')),
                ('ad', models.PositiveSmallIntegerField(verbose_name='АД')),
                ('hhs', models.PositiveSmallIntegerField(verbose_name='пульс')),
                ('create_at', models.DateTimeField(auto_now=True, unique=True, verbose_name='дата создания')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator', to='users.Patient', verbose_name='пациент')),
            ],
            options={
                'verbose_name': 'индикатор пациента',
                'verbose_name_plural': 'индикаторы пациентов',
            },
        ),
    ]
