# Generated by Django 2.2.5 on 2020-05-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientindicator',
            name='dyspnea',
            field=models.PositiveSmallIntegerField(choices=[(1, '- нет'), (2, '+ при нагрузке'), (3, '++ в покое')], verbose_name='одышка'),
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='heartbeat',
            field=models.PositiveSmallIntegerField(choices=[(1, '- нет'), (2, '+ при нагрузке'), (3, '++ в покое')], verbose_name='сердцебиение'),
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='position_bed',
            field=models.PositiveSmallIntegerField(choices=[(1, '- горизонтально'), (2, '+ высоко на 2х подушках'), (3, '++ сидя')], verbose_name='положение в постели'),
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='stack',
            field=models.PositiveSmallIntegerField(choices=[(1, '- стопы'), (2, '+ голени'), (3, '++ выше колени')], verbose_name='стеки в ноге'),
        ),
    ]
