# Generated by Django 2.2.5 on 2020-05-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20200501_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientindicator',
            name='dyspnea',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Нен'), (2, 'При нагрузке'), (3, 'В покое')], verbose_name='одышка'),
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='heartbeat',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Нет'), (2, 'При нагрузке'), (3, 'В покое')], verbose_name='сердцебиение'),
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='position_bed',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Горизонтально'), (2, 'Высоко на 2х подушках'), (3, 'Сидя')], verbose_name='положение в постели'),
        ),
        migrations.AlterField(
            model_name='patientindicator',
            name='stack',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Стопы'), (2, 'Голени'), (3, 'Выше колени')], verbose_name='отеки'),
        ),
    ]
