# Generated by Django 2.2.5 on 2020-05-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_auto_20200501_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientindicator',
            name='dyspnea',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Нет'), (2, 'При нагрузке'), (3, 'В покое')], verbose_name='одышка'),
        ),
    ]
