# Generated by Django 2.2.5 on 2020-05-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20200505_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientindicator',
            name='weight',
            field=models.PositiveSmallIntegerField(verbose_name='вес'),
        ),
    ]
