# Generated by Django 2.2.5 on 2020-05-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_auto_20200506_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientindicator',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата создания'),
        ),
    ]
