# Generated by Django 2.2.5 on 2020-05-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_auto_20200506_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientindicator',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='users.Patient', verbose_name='пациент'),
        ),
    ]
