# Generated by Django 2.2.5 on 2020-05-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_auto_20200508_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientindicator',
            name='deviation',
            field=models.PositiveIntegerField(default=0, verbose_name='отклонение'),
            preserve_default=False,
        ),
    ]
