# Generated by Django 2.2.5 on 2020-05-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_patientindicator_deviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientindicator',
            name='deviation',
            field=models.PositiveIntegerField(null=True, verbose_name='отклонение'),
        ),
    ]
