# Generated by Django 2.2.5 on 2020-05-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_auto_20200514_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientindicator',
            name='stack',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Нет'), (2, 'Стопы'), (3, 'Голени'), (4, 'Выше колени')], verbose_name='отеки'),
        ),
    ]
