# Generated by Django 2.2.5 on 2020-07-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0012_auto_20200521_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientindicator',
            options={'ordering': ['-create_at'], 'verbose_name': 'индикатор пациента', 'verbose_name_plural': 'индикаторы пациентов'},
        ),
    ]
