# Generated by Django 2.2.5 on 2020-07-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_auto_20200705_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientindicator',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
    ]
