# Generated by Django 2.2.5 on 2020-04-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_patientdocument_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdocument',
            options={'verbose_name': 'документ пациента', 'verbose_name_plural': 'документы пациентов'},
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='название документа'),
        ),
    ]
