# Generated by Django 2.2.5 on 2020-04-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_patient_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientIndicator',
        ),
    ]
