# Generated by Django 2.2.5 on 2020-04-23 17:01

from django.db import migrations, models
import utils.image_upload


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_patientindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.image_upload.upload_instance_image, verbose_name='фото'),
        ),
    ]
