# Generated by Django 2.2.5 on 2020-05-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200501_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызский')], default='ru', max_length=8, verbose_name='Язык'),
        ),
    ]
