# Generated by Django 2.2.5 on 2020-05-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='вес'),
        ),
    ]
