# Generated by Django 2.2.5 on 2020-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='notification',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во отклонений'),
            preserve_default=False,
        ),
    ]
