# Generated by Django 2.2.5 on 2020-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200502_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во отклонений'),
        ),
    ]
