# Generated by Django 2.2.5 on 2020-05-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20200502_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='count',
        ),
        migrations.AddField(
            model_name='notification',
            name='deviation_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во отклонений'),
        ),
    ]
