# Generated by Django 2.2.5 on 2020-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20200502_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотрено?'),
        ),
    ]
